name: Build-Apk

on:
  workflow_dispatch:

  push:
    branches:
      - 'master'
    tags-ignore:
      - 'v*'
    paths-ignore:
      - 'LICENSE'
      - '*.md'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v5
        with:
          working-directory: android

      - name: Build debug APK
        run: |
          chmod 777 ./gradlew
          ./gradlew app:assembleDebug
        working-directory: android

      - uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: 自动打tag
        run: |
          VERSION=$(grep -oP 'versionName\s*=\s*"\K[^"]+' app/build.gradle.kts || echo "")
          if [ -n "$VERSION" ]; then
            git config --local user.name "github-actions[bot]"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git tag -f v$VERSION
            git push origin v$VERSION --force
            echo "Tagged v$VERSION"
          fi
        working-directory: android
